// Generated by gencpp from file mavros/CommandTriggerControl.msg
// DO NOT EDIT!


#ifndef MAVROS_MESSAGE_COMMANDTRIGGERCONTROL_H
#define MAVROS_MESSAGE_COMMANDTRIGGERCONTROL_H

#include <ros/service_traits.h>


#include <mavros/CommandTriggerControlRequest.h>
#include <mavros/CommandTriggerControlResponse.h>


namespace mavros
{

struct CommandTriggerControl
{

typedef CommandTriggerControlRequest Request;
typedef CommandTriggerControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandTriggerControl
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::CommandTriggerControl > {
  static const char* value()
  {
    return "bd1399e8c77c84f4907ede27cbeacaf3";
  }

  static const char* value(const ::mavros::CommandTriggerControl&) { return value(); }
};

template<>
struct DataType< ::mavros::CommandTriggerControl > {
  static const char* value()
  {
    return "mavros/CommandTriggerControl";
  }

  static const char* value(const ::mavros::CommandTriggerControl&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::CommandTriggerControlRequest> should match 
// service_traits::MD5Sum< ::mavros::CommandTriggerControl > 
template<>
struct MD5Sum< ::mavros::CommandTriggerControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandTriggerControl >::value();
  }
  static const char* value(const ::mavros::CommandTriggerControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandTriggerControlRequest> should match 
// service_traits::DataType< ::mavros::CommandTriggerControl > 
template<>
struct DataType< ::mavros::CommandTriggerControlRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandTriggerControl >::value();
  }
  static const char* value(const ::mavros::CommandTriggerControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::CommandTriggerControlResponse> should match 
// service_traits::MD5Sum< ::mavros::CommandTriggerControl > 
template<>
struct MD5Sum< ::mavros::CommandTriggerControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandTriggerControl >::value();
  }
  static const char* value(const ::mavros::CommandTriggerControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandTriggerControlResponse> should match 
// service_traits::DataType< ::mavros::CommandTriggerControl > 
template<>
struct DataType< ::mavros::CommandTriggerControlResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandTriggerControl >::value();
  }
  static const char* value(const ::mavros::CommandTriggerControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_COMMANDTRIGGERCONTROL_H
