(cl:defpackage mav_msgs-msg
  (:use )
  (:export
   "<COMMANDTRAJECTORYVELOCITYYAWRATE>"
   "COMMANDTRAJECTORYVELOCITYYAWRATE"
   "<COMMANDROLLPITCHYAWRATETHRUST>"
   "COMMANDROLLPITCHYAWRATETHRUST"
   "<COMMANDATTITUDETHRUST>"
   "COMMANDATTITUDETHRUST"
   "<COMMANDMOTORSPEED>"
   "COMMANDMOTORSPEED"
   "<COMMANDRATETHRUST>"
   "COMMANDRATETHRUST"
   "<MOTORSPEED>"
   "MOTORSPEED"
   "<COMMANDTRAJECTORYPOSITIONYAW>"
   "COMMANDTRAJECTORYPOSITIONYAW"
  ))

